### DISCUSSION TITLE
エンジンは一つので，botのみ複数建てたい

### DISCUSSION THREAD

**Discussion by hvc101** [ciffelia/koe#171] [Q&A] [answered]
質問失礼します．
物凄く頭の悪い質問をしていたら申し訳ないのですが，botを複数立ち上げる際にエンジンを一つのみ立ちあげそこに複数のappからリクエストを送ることでマシンパワー節約したいのですが可能でしょうか？
また辞書機能や各ユーザの声設定を複数のbot間で連動させたいのですが可能でしょうか？

**Comment by ciffelia** [comment, marked as answer]
可能です。まずBotを1つだけ立ち上げる設定をした後に、次の手順でBotを増やしてください。

1. `koe.yaml`を`koe2.yaml`, `koe3.yaml`のようにコピーし、Discordのtoken設定をそれぞれ書き換えてください。redisやvoicevoxの設定はそのままにすることで、複数のBot間での共有が可能です。
2. `docker-compose.yaml`の`app`の項目をコピーし、`app2`, `app3`のようにする。それぞれ設定ファイルを`koe2.yaml`, `koe3.yaml`に変更する。

以上の手順を実行すると、`docker-compose.yaml`は次のようになるはずです。

```yaml
services:
  app:
    image: ghcr.io/ciffelia/koe:1.1.1
    init: true
    depends_on:
      redis:
        condition: service_healthy
      voicevox:
        condition: service_healthy
    restart: unless-stopped
    environment:
      RUST_LOG: warn
    volumes:
      - "./config/koe.yaml:/etc/koe.yaml:ro"

  app2:
    image: ghcr.io/ciffelia/koe:1.1.1
    init: true
    depends_on:
      redis:
        condition: service_healthy
      voicevox:
        condition: service_healthy
    restart: unless-stopped
    environment:
      RUST_LOG: warn
    volumes:
      - "./config/koe2.yaml:/etc/koe.yaml:ro"

  app3:
    image: ghcr.io/ciffelia/koe:1.1.1
    init: true
    depends_on:
      redis:
        condition: service_healthy
      voicevox:
        condition: service_healthy
    restart: unless-stopped
    environment:
      RUST_LOG: warn
    volumes:
      - "./config/koe3.yaml:/etc/koe.yaml:ro"

  redis:
    image: redis:7.2.4
    command: /usr/local/etc/redis/redis.conf
# 以下省略
```
