### ISSUE TITLE
GPU版を起動するとき、docker-compose.yml にdeployセクション、runtime nvidiaを追加することでエラーが解消した

### ISSUE THREAD

**Issue by amabile4** [ciffelia/koe#206]
docker-compose.ymlのvoicevox image の部分をnvidiaに書き換えたところ、イメージを読み込んだところエラーが発生しました
voicevoxサービスにdeployセクションを追加し、GPUの利用を指定したところエラーが解消されました。
cpuの部分をnvidiaに書き換える部分は自己責任かと思いますので、どう扱うのがよいかわからないのでissueにあげておきます

```
  voicevox:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-0.14.6
    restart: unless-stopped
    expose:
      - 50021
    volumes:
      - "./config/voicevox_presets.yaml:/opt/voicevox_engine/presets.yaml:ro"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "-O", "/dev/null", "http://localhost:50021/version"]
      interval: 10s
      timeout: 3s
      start_period: 1m
      start_interval: 3s
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
```
